=== ControllerSynthesis/CoSy/src/main/resources/cosy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--
    author: Sven Schneider
    copyright: all rights reserved, 2018
    -->

    <!-- TYPE_l2_l3_nonterminals__cons_l2 -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_l2_l3_nonterminals__cons_l2">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value1" type="xs:IDREF" use="required"/>
        <xs:attribute name="value2" type="xs:IDREF" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_l2_l3_nonterminals__cons_l2">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_l2_l3_nonterminals__cons_l2"/>
    </xs:complexType>

    <!-- TYPE_l2_l3_nonterminals__cons_l3 -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_l2_l3_nonterminals__cons_l3">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value1" type="xs:IDREF"/>
        <xs:attribute name="value2" type="xs:IDREF"/>
        <xs:attribute name="value3" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_l2_l3_nonterminals__cons_l3">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_l2_l3_nonterminals__cons_l3"/>
    </xs:complexType>

    <!-- TYPE_state_and_stack_or_state__cons_state -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_and_stack_or_state__cons_state">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_and_stack_or_state__cons_state">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_and_stack_or_state__cons_state"/>
    </xs:complexType>

    <!-- TYPE_state_and_stack_or_state__cons_state_and_stack -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_and_stack_or_state__cons_state_and_stack">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value1" type="xs:IDREF" use="required"/>
        <xs:attribute name="value2" type="xs:IDREF" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_and_stack_or_state__cons_state_and_stack">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_and_stack_or_state__cons_state_and_stack"/>
    </xs:complexType>

    <!-- TYPE_state_or_edge_nat__cons_state_or_edge_nat_new -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_or_edge_nat__cons_state_or_edge_nat_new">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value1" type="xs:IDREF"/>
        <xs:attribute name="value2" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_or_edge_nat__cons_state_or_edge_nat_new">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_or_edge_nat__cons_state_or_edge_nat_new"/>
    </xs:complexType>

    <!-- TYPE_state_or_edge_nat__cons_state_or_edge_nat_old -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_or_edge_nat__cons_state_or_edge_nat_old">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_or_edge_nat__cons_state_or_edge_nat_old">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_or_edge_nat__cons_state_or_edge_nat_old"/>
    </xs:complexType>

    <!-- TYPE_state_or_state__cons_state_or_state_new -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_or_state__cons_state_or_state_new">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_or_state__cons_state_or_state_new">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_or_state__cons_state_or_state_new"/>
    </xs:complexType>

    <!-- TYPE_state_or_state__cons_state_or_state_old -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_or_state__cons_state_or_state_old">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_or_state__cons_state_or_state_old">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_or_state__cons_state_or_state_old"/>
    </xs:complexType>

    <!-- TYPE_symbol__cons_symbol_base -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_symbol__cons_symbol_base">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_symbol__cons_symbol_base">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_symbol__cons_symbol_base"/>
    </xs:complexType>

    <!-- TYPE_symbol__cons_symbol_nat -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_symbol__cons_symbol_nat">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:integer"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_symbol__cons_symbol_nat">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_symbol__cons_symbol_nat"/>
    </xs:complexType>

    <!-- TYPE_state_or_edge__cons_state_or_edge_new -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_or_edge__cons_state_or_edge_new">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_or_edge__cons_state_or_edge_new">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_or_edge__cons_state_or_edge_new"/>
    </xs:complexType>

    <!-- TYPE_state_or_edge__cons_state_or_edge_old -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_or_edge__cons_state_or_edge_old">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_or_edge__cons_state_or_edge_old">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_or_edge__cons_state_or_edge_old"/>
    </xs:complexType>

    <!-- TYPE_tuple2 -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_tuple2">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value1" type="xs:IDREF"/>
        <xs:attribute name="value2" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_tuple2">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_tuple2"/>
    </xs:complexType>

    <!-- TYPE_tuple3 -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_tuple3">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value1" type="xs:IDREF"/>
        <xs:attribute name="value2" type="xs:IDREF"/>
        <xs:attribute name="value3" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_tuple3">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_tuple3"/>
    </xs:complexType>

    <!-- TYPE_two_elements__teA -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_two_elements__teA">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_two_elements__teA">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_two_elements__teA"/>
    </xs:complexType>

    <!-- TYPE_two_elements__teB -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_two_elements__teB">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_two_elements__teB">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_two_elements__teB"/>
    </xs:complexType>

    <!-- TYPE_string_symbol -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_string_symbol">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="string" type="xs:token" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_string_symbol">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_string_symbol"/>
    </xs:complexType>

    <!-- TYPE_epda_step_label -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_epda_step_label">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="edge_src" type="xs:IDREF" use="required"/>
        <xs:attribute name="edge_event" type="xs:IDREF" use="optional"/>
        <xs:attribute name="edge_pop" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="edge_push" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="edge_trg" type="xs:IDREF" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_epda_step_label">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_epda_step_label"/>
    </xs:complexType>

    <!-- TYPE_epda_step_label_reference -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_epda_step_label_reference">
        <xs:attribute name="ref" type="xs:IDREF" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_epda_step_label_reference">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_epda_step_label_reference"/>
    </xs:complexType>

    <!-- TYPE_epda -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_epda">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="epda_states" type="xs:IDREFS" use="required"/>
        <xs:attribute name="epda_events" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="epda_gamma" type="xs:IDREFS" use="required"/>
        <xs:attribute name="epda_delta" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="epda_initial" type="xs:IDREF" use="required"/>
        <xs:attribute name="epda_eos" type="xs:IDREF" use="required"/>
        <xs:attribute name="epda_marking" type="xs:IDREFS" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_epda">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_epda"/>
    </xs:complexType>

    <!-- TYPE_cfg_step_label -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_cfg_step_label">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="prod_lhs" type="xs:IDREF" use="required"/>
        <xs:attribute name="prod_rhs" type="xs:IDREFS" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_cfg_step_label">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_cfg_step_label"/>
    </xs:complexType>

    <!-- TYPE_cfg -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_cfg">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="cfg_nonterminals" type="xs:IDREFS" use="required"/>
        <xs:attribute name="cfg_events" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="cfg_initial" type="xs:IDREF" use="required"/>
        <xs:attribute name="cfg_step_labels" type="xs:IDREFS" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_cfg">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_cfg"/>
    </xs:complexType>

    <!-- TYPE_parser_step_label -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_parser_step_label">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="rule_lpop" type="xs:IDREFS" use="required"/>
        <xs:attribute name="rule_rpop" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="rule_lpush" type="xs:IDREFS" use="required"/>
        <xs:attribute name="rule_rpush" type="xs:IDREFS" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_parser_step_label">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_parser_step_label"/>
    </xs:complexType>

    <!-- TYPE_parser -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_parser">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="parser_nonterms" type="xs:IDREFS" use="required"/>
        <xs:attribute name="parser_events" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="parser_initial" type="xs:IDREF" use="required"/>
        <xs:attribute name="parser_marking" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="parser_step_labels" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="parser_eoi" type="xs:IDREF" use="required"/>
        <xs:attribute name="parser_marker" type="xs:IDREFS" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_parser">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_parser"/>
    </xs:complexType>

    <!-- TYPE_sigma_uncontrollable -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_sigma_uncontrollable">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="elements" type="xs:IDREFS" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_sigma_uncontrollable">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_sigma_uncontrollable"/>
    </xs:complexType>

    <!-- TYPE_test_sequence -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_test_sequence">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="expected" type="xs:string" use="required"/>
        <xs:attribute name="sequence" type="xs:IDREFS" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_test_sequence">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_test_sequence"/>
    </xs:complexType>

    <!-- TYPE_test_sequences -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_test_sequences">
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_test_sequences">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="test_sequence" type="TYPE_test_sequence"/>
            </xs:choice>
        </xs:sequence>
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_test_sequences"/>
    </xs:complexType>

    <!-- root -->

    <xs:complexType name="TYPE_root">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="root" type="TYPE_root"/>
                <xs:element name="string_symbol" type="TYPE_string_symbol"/>
                <xs:element name="l2_l3_nonterminals__cons_l2" type="TYPE_l2_l3_nonterminals__cons_l2"/>
                <xs:element name="l2_l3_nonterminals__cons_l3" type="TYPE_l2_l3_nonterminals__cons_l3"/>
                <xs:element name="state_and_stack_or_state__cons_state"
                            type="TYPE_state_and_stack_or_state__cons_state"/>
                <xs:element name="state_and_stack_or_state__cons_state_and_stack"
                            type="TYPE_state_and_stack_or_state__cons_state_and_stack"/>
                <xs:element name="state_or_edge__cons_state_or_edge_new"
                            type="TYPE_state_or_edge__cons_state_or_edge_new"/>
                <xs:element name="state_or_edge__cons_state_or_edge_old"
                            type="TYPE_state_or_edge__cons_state_or_edge_old"/>
                <xs:element name="state_or_edge_nat__cons_state_or_edge_nat_new"
                            type="TYPE_state_or_edge_nat__cons_state_or_edge_nat_new"/>
                <xs:element name="state_or_edge_nat__cons_state_or_edge_nat_old"
                            type="TYPE_state_or_edge_nat__cons_state_or_edge_nat_old"/>
                <xs:element name="state_or_state__cons_state_or_state_new"
                            type="TYPE_state_or_state__cons_state_or_state_new"/>
                <xs:element name="state_or_state__cons_state_or_state_old"
                            type="TYPE_state_or_state__cons_state_or_state_old"/>
                <xs:element name="symbol__cons_symbol_base" type="TYPE_symbol__cons_symbol_base"/>
                <xs:element name="symbol__cons_symbol_nat" type="TYPE_symbol__cons_symbol_nat"/>
                <xs:element name="tuple2" type="TYPE_tuple2"/>
                <xs:element name="tuple3" type="TYPE_tuple3"/>
                <xs:element name="two_elements__teA" type="TYPE_two_elements__teA"/>
                <xs:element name="two_elements__teB" type="TYPE_two_elements__teB"/>
                <xs:element name="epda_step_label"
                            type="TYPE_epda_step_label"/>
                <xs:element name="epda" type="TYPE_epda"/>
                <xs:element name="cfg_step_label" type="TYPE_cfg_step_label"/>
                <xs:element name="cfg" type="TYPE_cfg"/>
                <xs:element name="parser_step_label" type="TYPE_parser_step_label"/>
                <xs:element name="parser" type="TYPE_parser"/>
                <xs:element name="sigma_uncontrollable" type="TYPE_sigma_uncontrollable"/>
                <xs:element name="test_sequences" type="TYPE_test_sequences"/>

            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="root" type="TYPE_root"/>

</xs:schema>

=== ControllerSynthesis/CoSy/src/test/resources/unit_tests/p01__ENFORCE_BLOCKFREE__T04_CFG_FIRST_vs_T04_CFG_FIRST2_2.xml
<?xml version="1.0"?>
<root
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../main/resources/cosy.xsd">

    <!--
    author: Sven Schneider
    copyright: all rights reserved, 2018
    -->

    <string_symbol id="event_0" string="e0"/>
    <string_symbol id="event_1" string="e1"/>
    <string_symbol id="event_2" string="e2"/>

    <two_elements__teB id="e0" value="event_0"/>
    <two_elements__teB id="e1" value="event_1"/>
    <two_elements__teB id="e2" value="event_2"/>

    <string_symbol id="nonterminal_N0" string="N0"/>
    <string_symbol id="nonterminal_N1" string="N1"/>
    <string_symbol id="nonterminal_N2" string="N2"/>
    <string_symbol id="nonterminal_N3" string="N3"/>
    <string_symbol id="nonterminal_N4" string="N4"/>
    <string_symbol id="nonterminal_N5" string="N5"/>
    <string_symbol id="nonterminal_N6" string="N6"/>

    <two_elements__teA id="N0" value="nonterminal_N0"/>
    <two_elements__teA id="N1" value="nonterminal_N1"/>
    <two_elements__teA id="N2" value="nonterminal_N2"/>
    <two_elements__teA id="N3" value="nonterminal_N3"/>
    <two_elements__teA id="N4" value="nonterminal_N4"/>
    <two_elements__teA id="N5" value="nonterminal_N5"/>
    <two_elements__teA id="N6" value="nonterminal_N6"/>

    <cfg_step_label id="prod_00" prod_lhs="nonterminal_N3" prod_rhs="e0 N4 e0"/>
    <cfg_step_label id="prod_01" prod_lhs="nonterminal_N4" prod_rhs="e1 N5"/>
    <cfg_step_label id="prod_02" prod_lhs="nonterminal_N5" prod_rhs="N0 N6"/>
    <cfg_step_label id="prod_03" prod_lhs="nonterminal_N0" prod_rhs="N1 N1"/>
    <cfg_step_label id="prod_04" prod_lhs="nonterminal_N6" prod_rhs="e2 N1"/>
    <cfg_step_label id="prod_05" prod_lhs="nonterminal_N1"/>

    <cfg
            id="input"
            cfg_nonterminals="nonterminal_N0 nonterminal_N1 nonterminal_N2 nonterminal_N3 nonterminal_N4 nonterminal_N5 nonterminal_N6"
            cfg_events="event_0 event_1 event_2"
            cfg_initial="nonterminal_N3"
            cfg_step_labels="prod_00 prod_01 prod_02 prod_03 prod_04 prod_05"/>

</root>

=== ControllerSynthesis/CoSy/src/test/resources/unit_tests/a2n_b2n.xml
<?xml version="1.0"?>
<root
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../main/resources/cosy.xsd">

    <!--
    author: Sven Schneider
    copyright: all rights reserved, 2018
    -->

    <!-- EPDA -->
    <string_symbol id="event_a" string="a"/>
    <string_symbol id="event_b" string="b"/>
    <string_symbol id="box" string="☐"/>
    <string_symbol id="bullet" string="•"/>
    <string_symbol id="state_0" string="q0"/>
    <string_symbol id="state_1" string="q1"/>
    <string_symbol id="state_2" string="q2"/>
    <string_symbol id="state_3" string="q3"/>
    <epda_step_label id="edge_0" edge_src="state_0" edge_event="event_a" edge_pop="box"
                     edge_push="bullet box" edge_trg="state_1"/>
    <epda_step_label id="edge_1" edge_src="state_1" edge_event="event_a" edge_pop="bullet"
                     edge_push="bullet bullet" edge_trg="state_1"/>
    <epda_step_label id="edge_2" edge_src="state_1" edge_event="event_b" edge_pop="bullet"
                     edge_trg="state_2"/>
    <epda_step_label id="edge_3" edge_src="state_2" edge_event="event_b" edge_pop="bullet"
                     edge_trg="state_2"/>
    <epda_step_label id="edge_4" edge_src="state_2" edge_pop="box" edge_push="box"
                     edge_trg="state_3"/>
    <epda
            id="dpda__a2n_b2n"
            epda_states="state_0 state_1 state_2 state_3"
            epda_events="event_a event_b"
            epda_gamma="box bullet"
            epda_delta="edge_0 edge_1 edge_2 edge_3 edge_4"
            epda_initial="state_0"
            epda_eos="box"
            epda_marking="state_0 state_3"/>

    <!-- CFG -->
    <string_symbol id="nonterminal_0" string="S"/>
    <two_elements__teB id="beB_event_a" value="event_a"/>
    <two_elements__teA id="beA_nonterminal_0" value="nonterminal_0"/>
    <two_elements__teB id="beB_event_b" value="event_b"/>
    <cfg_step_label id="prod_0" prod_lhs="nonterminal_0" prod_rhs="beB_event_a beA_nonterminal_0 beB_event_b"/>
    <cfg_step_label id="prod_1" prod_lhs="nonterminal_0"/>
    <cfg
            id="cfg__a2n_b2n"
            cfg_nonterminals="nonterminal_0"
            cfg_events="event_a event_b"
            cfg_initial="nonterminal_0"
            cfg_step_labels="prod_0 prod_1"/>

    <!-- PARSER -->
    <string_symbol id="nonterminal_1" string="S1"/>
    <string_symbol id="nonterminal_2" string="S2"/>
    <string_symbol id="nonterminal_3" string="S3"/>
    <string_symbol id="nonterminal_box" string="S☐"/>
    <string_symbol id="nonterminal_bullet" string="S•"/>
    <string_symbol id="event_END" string="$"/>
    <parser_step_label id="rule_0" rule_lpop="nonterminal_0" rule_lpush="nonterminal_box nonterminal_0"/>
    <parser_step_label id="rule_1" rule_lpop="nonterminal_0" rule_rpop="event_a"
                       rule_lpush="nonterminal_bullet nonterminal_1"
    />
    <parser_step_label id="rule_2" rule_lpop="nonterminal_1" rule_rpop="event_a"
                       rule_lpush="nonterminal_bullet nonterminal_1"
    />
    <parser_step_label id="rule_3" rule_lpop="nonterminal_bullet nonterminal_1" rule_rpop="event_b"
                       rule_lpush="nonterminal_2"
    />
    <parser_step_label id="rule_4" rule_lpop="nonterminal_bullet nonterminal_2" rule_rpop="event_b"
                       rule_lpush="nonterminal_2"
    />
    <parser_step_label id="rule_5" rule_lpop="nonterminal_box nonterminal_2" rule_lpush="nonterminal_3"
    />
    <parser
            id="parser__a2n_b2n"
            parser_nonterms="nonterminal_0 nonterminal_1 nonterminal_2 nonterminal_3 nonterminal_box nonterminal_bullet"
            parser_events="event_a event_b event_END"
            parser_initial="nonterminal_0"
            parser_marking="nonterminal_0 nonterminal_3"
            parser_step_labels="rule_0 rule_1 rule_2 rule_3 rule_4 rule_5"
            parser_eoi="event_END"/>
</root>

=== ControllerSynthesis/CoSy/src/test/resources/unit_tests/p01__ENFORCE_BLOCKFREE__T06_02_02_EDPDA_REMOVE_MASS_POPPING_EDGES___FUNEDPDARMPOE_example1.xml
<?xml version="1.0"?>
<root
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../main/resources/cosy.xsd">

    <!--
    author: Sven Schneider
    copyright: all rights reserved, 2018
    -->

    <string_symbol id="event_a" string="a"/>
    <string_symbol id="event_b" string="b"/>
    <string_symbol id="box" string="☐"/>
    <string_symbol id="bullet" string="•"/>
    <string_symbol id="circ" string="○"/>
    <string_symbol id="state_0" string="q0"/>
    <string_symbol id="state_1" string="q1"/>
    <string_symbol id="state_2" string="q2"/>
    <string_symbol id="state_3" string="q3"/>

    <epda_step_label id="edge_0"
                     edge_src="state_0"
                     edge_event="event_a"
                     edge_pop="box"
                     edge_push="circ circ box"
                     edge_trg="state_1"/>
    <epda_step_label id="edge_1"
                     edge_src="state_0"
                     edge_event="event_b"
                     edge_pop="box"
                     edge_push="circ box"
                     edge_trg="state_1"/>
    <epda_step_label id="edge_2"
                     edge_src="state_1"
                     edge_event="event_a"
                     edge_pop="circ circ"
                     edge_push="circ"
                     edge_trg="state_2"/>
    <epda_step_label id="edge_3"
                     edge_src="state_1"
                     edge_event="event_b"
                     edge_pop="circ box"
                     edge_push="bullet box"
                     edge_trg="state_3"/>

    <epda
            id="input"
            epda_states="state_0 state_1 state_2 state_3"
            epda_events="event_a event_b"
            epda_gamma="box bullet circ"
            epda_delta="edge_0 edge_1 edge_2 edge_3"
            epda_initial="state_0"
            epda_eos="box"
            epda_marking="state_2 state_3"/>

</root>

=== ControllerSynthesis/CoSy/src/test/resources/unit_tests/p01__ENFORCE_BLOCKFREE__T05_04_LR_MACHINE___FUNLRMACHINE_example3.xml
<?xml version="1.0"?>
<root
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../main/resources/cosy.xsd">

    <!--
    author: Sven Schneider
    copyright: all rights reserved, 2018
    -->

    <string_symbol id="event_a" string="a"/>
    <string_symbol id="event_b" string="b"/>
    <string_symbol id="event_c" string="c"/>
    <two_elements__teB id="a" value="event_a"/>
    <two_elements__teB id="b" value="event_b"/>
    <two_elements__teB id="c" value="event_c"/>

    <string_symbol id="nonterminal_S" string="S"/>
    <string_symbol id="nonterminal_A" string="A"/>
    <string_symbol id="nonterminal_B" string="B"/>
    <string_symbol id="nonterminal_AX" string="AX"/>
    <string_symbol id="nonterminal_BX" string="BX"/>
    <two_elements__teA id="S" value="nonterminal_S"/>
    <two_elements__teA id="A" value="nonterminal_A"/>
    <two_elements__teA id="B" value="nonterminal_B"/>
    <two_elements__teA id="AX" value="nonterminal_AX"/>
    <two_elements__teA id="BX" value="nonterminal_BX"/>

    <cfg_step_label id="prod_1" prod_lhs="nonterminal_S" prod_rhs="A"/>
    <cfg_step_label id="prod_2" prod_lhs="nonterminal_S" prod_rhs="B"/>
    <cfg_step_label id="prod_3" prod_lhs="nonterminal_A" prod_rhs="a A a"/>
    <cfg_step_label id="prod_4" prod_lhs="nonterminal_A" prod_rhs="AX"/>
    <cfg_step_label id="prod_5" prod_lhs="nonterminal_AX" prod_rhs="b AX"/>
    <cfg_step_label id="prod_6" prod_lhs="nonterminal_AX" prod_rhs="c"/>
    <cfg_step_label id="prod_7" prod_lhs="nonterminal_B" prod_rhs="a B"/>
    <cfg_step_label id="prod_8" prod_lhs="nonterminal_B" prod_rhs="BX"/>
    <cfg_step_label id="prod_9" prod_lhs="nonterminal_BX" prod_rhs="b BX b"/>
    <cfg_step_label id="prod_10" prod_lhs="nonterminal_BX" prod_rhs="c"/>
    <cfg
            id="input"
            cfg_nonterminals="nonterminal_S nonterminal_A nonterminal_AX nonterminal_B nonterminal_BX"
            cfg_events="event_a event_b event_c"
            cfg_initial="nonterminal_S"
            cfg_step_labels="prod_1 prod_2 prod_3 prod_4 prod_5 prod_6 prod_7 prod_8 prod_9 prod_10"/>

</root>
