=== ControllerSynthesis/CoSy/src/main/resources/cosy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--
    author: Sven Schneider
    copyright: all rights reserved, 2018
    -->

    <!-- TYPE_l2_l3_nonterminals__cons_l2 -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_l2_l3_nonterminals__cons_l2">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value1" type="xs:IDREF" use="required"/>
        <xs:attribute name="value2" type="xs:IDREF" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_l2_l3_nonterminals__cons_l2">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_l2_l3_nonterminals__cons_l2"/>
    </xs:complexType>

    <!-- TYPE_l2_l3_nonterminals__cons_l3 -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_l2_l3_nonterminals__cons_l3">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value1" type="xs:IDREF"/>
        <xs:attribute name="value2" type="xs:IDREF"/>
        <xs:attribute name="value3" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_l2_l3_nonterminals__cons_l3">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_l2_l3_nonterminals__cons_l3"/>
    </xs:complexType>

    <!-- TYPE_state_and_stack_or_state__cons_state -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_and_stack_or_state__cons_state">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_and_stack_or_state__cons_state">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_and_stack_or_state__cons_state"/>
    </xs:complexType>

    <!-- TYPE_state_and_stack_or_state__cons_state_and_stack -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_and_stack_or_state__cons_state_and_stack">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value1" type="xs:IDREF" use="required"/>
        <xs:attribute name="value2" type="xs:IDREF" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_and_stack_or_state__cons_state_and_stack">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_and_stack_or_state__cons_state_and_stack"/>
    </xs:complexType>

    <!-- TYPE_state_or_edge_nat__cons_state_or_edge_nat_new -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_or_edge_nat__cons_state_or_edge_nat_new">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value1" type="xs:IDREF"/>
        <xs:attribute name="value2" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_or_edge_nat__cons_state_or_edge_nat_new">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_or_edge_nat__cons_state_or_edge_nat_new"/>
    </xs:complexType>

    <!-- TYPE_state_or_edge_nat__cons_state_or_edge_nat_old -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_or_edge_nat__cons_state_or_edge_nat_old">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_or_edge_nat__cons_state_or_edge_nat_old">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_or_edge_nat__cons_state_or_edge_nat_old"/>
    </xs:complexType>

    <!-- TYPE_state_or_state__cons_state_or_state_new -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_or_state__cons_state_or_state_new">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_or_state__cons_state_or_state_new">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_or_state__cons_state_or_state_new"/>
    </xs:complexType>

    <!-- TYPE_state_or_state__cons_state_or_state_old -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_or_state__cons_state_or_state_old">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_or_state__cons_state_or_state_old">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_or_state__cons_state_or_state_old"/>
    </xs:complexType>

    <!-- TYPE_symbol__cons_symbol_base -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_symbol__cons_symbol_base">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_symbol__cons_symbol_base">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_symbol__cons_symbol_base"/>
    </xs:complexType>

    <!-- TYPE_symbol__cons_symbol_nat -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_symbol__cons_symbol_nat">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:integer"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_symbol__cons_symbol_nat">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_symbol__cons_symbol_nat"/>
    </xs:complexType>

    <!-- TYPE_state_or_edge__cons_state_or_edge_new -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_or_edge__cons_state_or_edge_new">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_or_edge__cons_state_or_edge_new">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_or_edge__cons_state_or_edge_new"/>
    </xs:complexType>

    <!-- TYPE_state_or_edge__cons_state_or_edge_old -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_state_or_edge__cons_state_or_edge_old">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_state_or_edge__cons_state_or_edge_old">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_state_or_edge__cons_state_or_edge_old"/>
    </xs:complexType>

    <!-- TYPE_tuple2 -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_tuple2">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value1" type="xs:IDREF"/>
        <xs:attribute name="value2" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_tuple2">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_tuple2"/>
    </xs:complexType>

    <!-- TYPE_tuple3 -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_tuple3">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value1" type="xs:IDREF"/>
        <xs:attribute name="value2" type="xs:IDREF"/>
        <xs:attribute name="value3" type="xs:IDREF"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_tuple3">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_tuple3"/>
    </xs:complexType>

    <!-- TYPE_two_elements__teA -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_two_elements__teA">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_two_elements__teA">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_two_elements__teA"/>
    </xs:complexType>

    <!-- TYPE_two_elements__teB -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_two_elements__teB">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="value" type="xs:IDREF" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_two_elements__teB">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_two_elements__teB"/>
    </xs:complexType>

    <!-- TYPE_string_symbol -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_string_symbol">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="string" type="xs:token" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_string_symbol">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_string_symbol"/>
    </xs:complexType>

    <!-- TYPE_epda_step_label -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_epda_step_label">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="edge_src" type="xs:IDREF" use="required"/>
        <xs:attribute name="edge_event" type="xs:IDREF" use="optional"/>
        <xs:attribute name="edge_pop" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="edge_push" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="edge_trg" type="xs:IDREF" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_epda_step_label">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_epda_step_label"/>
    </xs:complexType>

    <!-- TYPE_epda_step_label_reference -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_epda_step_label_reference">
        <xs:attribute name="ref" type="xs:IDREF" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_epda_step_label_reference">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_epda_step_label_reference"/>
    </xs:complexType>

    <!-- TYPE_epda -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_epda">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="epda_states" type="xs:IDREFS" use="required"/>
        <xs:attribute name="epda_events" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="epda_gamma" type="xs:IDREFS" use="required"/>
        <xs:attribute name="epda_delta" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="epda_initial" type="xs:IDREF" use="required"/>
        <xs:attribute name="epda_eos" type="xs:IDREF" use="required"/>
        <xs:attribute name="epda_marking" type="xs:IDREFS" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_epda">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_epda"/>
    </xs:complexType>

    <!-- TYPE_cfg_step_label -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_cfg_step_label">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="prod_lhs" type="xs:IDREF" use="required"/>
        <xs:attribute name="prod_rhs" type="xs:IDREFS" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_cfg_step_label">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_cfg_step_label"/>
    </xs:complexType>

    <!-- TYPE_cfg -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_cfg">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="cfg_nonterminals" type="xs:IDREFS" use="required"/>
        <xs:attribute name="cfg_events" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="cfg_initial" type="xs:IDREF" use="required"/>
        <xs:attribute name="cfg_step_labels" type="xs:IDREFS" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_cfg">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_cfg"/>
    </xs:complexType>

    <!-- TYPE_parser_step_label -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_parser_step_label">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="rule_lpop" type="xs:IDREFS" use="required"/>
        <xs:attribute name="rule_rpop" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="rule_lpush" type="xs:IDREFS" use="required"/>
        <xs:attribute name="rule_rpush" type="xs:IDREFS" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_parser_step_label">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_parser_step_label"/>
    </xs:complexType>

    <!-- TYPE_parser -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_parser">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="parser_nonterms" type="xs:IDREFS" use="required"/>
        <xs:attribute name="parser_events" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="parser_initial" type="xs:IDREF" use="required"/>
        <xs:attribute name="parser_marking" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="parser_step_labels" type="xs:IDREFS" use="optional"/>
        <xs:attribute name="parser_eoi" type="xs:IDREF" use="required"/>
        <xs:attribute name="parser_marker" type="xs:IDREFS" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_parser">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_parser"/>
    </xs:complexType>

    <!-- TYPE_sigma_uncontrollable -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_sigma_uncontrollable">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="elements" type="xs:IDREFS" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_sigma_uncontrollable">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_sigma_uncontrollable"/>
    </xs:complexType>

    <!-- TYPE_test_sequence -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_test_sequence">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="expected" type="xs:string" use="required"/>
        <xs:attribute name="sequence" type="xs:IDREFS" use="optional"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_test_sequence">
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_test_sequence"/>
    </xs:complexType>

    <!-- TYPE_test_sequences -->

    <xs:attributeGroup name="ATTRIBUTES_TYPE_test_sequences">
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:attributeGroup>

    <xs:complexType name="TYPE_test_sequences">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="test_sequence" type="TYPE_test_sequence"/>
            </xs:choice>
        </xs:sequence>
        <xs:attributeGroup ref="ATTRIBUTES_TYPE_test_sequences"/>
    </xs:complexType>

    <!-- root -->

    <xs:complexType name="TYPE_root">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="root" type="TYPE_root"/>
                <xs:element name="string_symbol" type="TYPE_string_symbol"/>
                <xs:element name="l2_l3_nonterminals__cons_l2" type="TYPE_l2_l3_nonterminals__cons_l2"/>
                <xs:element name="l2_l3_nonterminals__cons_l3" type="TYPE_l2_l3_nonterminals__cons_l3"/>
                <xs:element name="state_and_stack_or_state__cons_state"
                            type="TYPE_state_and_stack_or_state__cons_state"/>
                <xs:element name="state_and_stack_or_state__cons_state_and_stack"
                            type="TYPE_state_and_stack_or_state__cons_state_and_stack"/>
                <xs:element name="state_or_edge__cons_state_or_edge_new"
                            type="TYPE_state_or_edge__cons_state_or_edge_new"/>
                <xs:element name="state_or_edge__cons_state_or_edge_old"
                            type="TYPE_state_or_edge__cons_state_or_edge_old"/>
                <xs:element name="state_or_edge_nat__cons_state_or_edge_nat_new"
                            type="TYPE_state_or_edge_nat__cons_state_or_edge_nat_new"/>
                <xs:element name="state_or_edge_nat__cons_state_or_edge_nat_old"
                            type="TYPE_state_or_edge_nat__cons_state_or_edge_nat_old"/>
                <xs:element name="state_or_state__cons_state_or_state_new"
                            type="TYPE_state_or_state__cons_state_or_state_new"/>
                <xs:element name="state_or_state__cons_state_or_state_old"
                            type="TYPE_state_or_state__cons_state_or_state_old"/>
                <xs:element name="symbol__cons_symbol_base" type="TYPE_symbol__cons_symbol_base"/>
                <xs:element name="symbol__cons_symbol_nat" type="TYPE_symbol__cons_symbol_nat"/>
                <xs:element name="tuple2" type="TYPE_tuple2"/>
                <xs:element name="tuple3" type="TYPE_tuple3"/>
                <xs:element name="two_elements__teA" type="TYPE_two_elements__teA"/>
                <xs:element name="two_elements__teB" type="TYPE_two_elements__teB"/>
                <xs:element name="epda_step_label"
                            type="TYPE_epda_step_label"/>
                <xs:element name="epda" type="TYPE_epda"/>
                <xs:element name="cfg_step_label" type="TYPE_cfg_step_label"/>
                <xs:element name="cfg" type="TYPE_cfg"/>
                <xs:element name="parser_step_label" type="TYPE_parser_step_label"/>
                <xs:element name="parser" type="TYPE_parser"/>
                <xs:element name="sigma_uncontrollable" type="TYPE_sigma_uncontrollable"/>
                <xs:element name="test_sequences" type="TYPE_test_sequences"/>

            </xs:choice>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="root" type="TYPE_root"/>

</xs:schema>

=== ControllerSynthesis/CoSy/src/test/resources/unit_tests/example_of_nontermination.xml
<?xml version="1.0"?>
<root
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../main/resources/cosy.xsd">

    <!--
    author: Sven Schneider
    copyright: all rights reserved, 2018
    -->

    <string_symbol id="event_a" string="a"/>
    <string_symbol id="event_b" string="b"/>
    <string_symbol id="event_u" string="u"/>

    <string_symbol id="box" string="☐"/>
    <string_symbol id="bullet" string="•"/>
    <string_symbol id="state_0" string="q0"/>
    <string_symbol id="state_1" string="q1"/>
    <string_symbol id="state_2" string="q2"/>

    <epda_step_label id="edge_0" edge_src="state_0" edge_event="event_b" edge_pop="box" edge_push="bullet box"
                     edge_trg="state_0"/>
    <epda_step_label id="edge_1" edge_src="state_0" edge_event="event_b" edge_pop="bullet" edge_push="bullet bullet"
                     edge_trg="state_0"/>
    <epda_step_label id="edge_2" edge_src="state_0" edge_event="event_a" edge_pop="box" edge_push="box"
                     edge_trg="state_1"/>
    <epda_step_label id="edge_3" edge_src="state_0" edge_event="event_a" edge_pop="bullet" edge_push="bullet"
                     edge_trg="state_1"/>
    <epda_step_label id="edge_4" edge_src="state_1" edge_event="event_u" edge_pop="bullet" edge_trg="state_2"/>
    <epda_step_label id="edge_5" edge_src="state_2" edge_event="event_a" edge_pop="bullet" edge_push="bullet"
                     edge_trg="state_1"/>
    <epda_step_label id="edge_6" edge_src="state_2" edge_event="event_a" edge_pop="box" edge_push="box"
                     edge_trg="state_1"/>

    <epda
            id="spec"
            epda_states="state_0 state_1 state_2"
            epda_events="event_a event_b event_u"
            epda_gamma="box bullet"
            epda_delta="edge_0 edge_1 edge_2 edge_3 edge_4 edge_5 edge_6"
            epda_initial="state_0"
            epda_eos="box"
            epda_marking="state_1"/>

    <epda_step_label id="edgep_0" edge_src="state_0" edge_event="event_b" edge_pop="box" edge_push="box"
                     edge_trg="state_0"/>
    <epda_step_label id="edgep_1" edge_src="state_0" edge_event="event_a" edge_pop="box" edge_push="box"
                     edge_trg="state_1"/>
    <epda_step_label id="edgep_2" edge_src="state_1" edge_event="event_u" edge_pop="box" edge_push="box"
                     edge_trg="state_2"/>
    <epda_step_label id="edgep_3" edge_src="state_2" edge_event="event_a" edge_pop="box" edge_push="box"
                     edge_trg="state_1"/>

    <epda
            id="plant"
            epda_states="state_0 state_1 state_2"
            epda_events="event_a event_b event_u"
            epda_gamma="box"
            epda_delta="edgep_0 edgep_1 edgep_2 edgep_3"
            epda_initial="state_0"
            epda_eos="box"
            epda_marking="state_1"/>

    <!-- sigmaUC -->
    <sigma_uncontrollable id="sigmaUC" elements="event_u"/>

</root>

=== ControllerSynthesis/CoSy/src/test/resources/unit_tests/p01__ENFORCE_BLOCKFREE__T06_02_02_EDPDA_REMOVE_MASS_POPPING_EDGES___extra6.xml
<?xml version="1.0"?>
<root
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../main/resources/cosy.xsd">

    <!--
    author: Sven Schneider
    copyright: all rights reserved, 2018
    -->

    <string_symbol id="event_F" string="F"/>
    <string_symbol id="event_S" string="S"/>
    <string_symbol id="event_B1" string="B1"/>
    <string_symbol id="event_B2" string="B2"/>
    <string_symbol id="event_A" string="A"/>
    <string_symbol id="box" string="☐"/>
    <string_symbol id="bullet" string="•"/>
    <string_symbol id="circ" string="○"/>

    <string_symbol id="state_q1" string="q1"/>
    <string_symbol id="state_q2" string="q2"/>
    <string_symbol id="state_q3" string="q3"/>
    <string_symbol id="state_q4" string="q4"/>
    <epda_step_label id="edge_spec_0" edge_src="state_q1" edge_event="event_A" edge_pop="box" edge_push="bullet box"
                     edge_trg="state_q1"/>
    <epda_step_label id="edge_spec_1" edge_src="state_q1" edge_event="event_A" edge_pop="bullet"
                     edge_push="bullet bullet" edge_trg="state_q1"/>
    <epda_step_label id="edge_spec_2" edge_src="state_q1" edge_event="event_A" edge_pop="circ" edge_trg="state_q1"/>
    <epda_step_label id="edge_spec_3" edge_src="state_q1" edge_event="event_B1" edge_pop="box" edge_push="circ box"
                     edge_trg="state_q1"/>
    <epda_step_label id="edge_spec_4" edge_src="state_q1" edge_event="event_B1" edge_pop="bullet bullet"
                     edge_push="bullet" edge_trg="state_q1"/>
    <epda_step_label id="edge_spec_5" edge_src="state_q1" edge_event="event_B1" edge_pop="circ" edge_push="circ circ"
                     edge_trg="state_q1"/>
    <epda_step_label id="edge_spec_6" edge_src="state_q1" edge_event="event_B2" edge_pop="box" edge_push="circ box"
                     edge_trg="state_q1"/>
    <epda_step_label id="edge_spec_7" edge_src="state_q1" edge_event="event_B2" edge_pop="bullet" edge_trg="state_q1"/>
    <epda_step_label id="edge_spec_8" edge_src="state_q1" edge_event="event_B2" edge_pop="circ" edge_push="circ circ"
                     edge_trg="state_q1"/>
    <epda
            id="input"
            epda_states="state_q1 state_q2 state_q3 state_q4"
            epda_events="event_F event_S event_B1 event_B2 event_A"
            epda_gamma="box bullet circ"
            epda_delta="
            edge_spec_0
            edge_spec_1
            edge_spec_2
            edge_spec_3
            edge_spec_4
            edge_spec_5
            edge_spec_6
            edge_spec_7
            edge_spec_8
            "
            epda_initial="state_q1"
            epda_eos="box"
            epda_marking="state_q3"/>


</root>

=== ControllerSynthesis/CoSy/src/test/resources/unit_tests/p01__ENFORCE_BLOCKFREE__T03_06_04_CFG_ENFORCE_ACCESSIBILITY__F_CFGEA_example.xml
<?xml version="1.0"?>
<root
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../main/resources/cosy.xsd">

    <!--
    author: Sven Schneider
    copyright: all rights reserved, 2018
    -->

    <string_symbol id="event_a" string="a"/>
    <string_symbol id="event_b" string="b"/>
    <string_symbol id="nonterminal_S" string="S"/>
    <string_symbol id="nonterminal_P" string="P"/>
    <string_symbol id="nonterminal_A" string="A"/>

    <two_elements__teB id="a" value="event_a"/>
    <two_elements__teB id="b" value="event_b"/>

    <two_elements__teA id="S" value="nonterminal_S"/>
    <two_elements__teA id="P" value="nonterminal_P"/>
    <two_elements__teA id="A" value="nonterminal_A"/>
    <cfg_step_label id="prod_0" prod_lhs="nonterminal_S"/>
    <cfg_step_label id="prod_1" prod_lhs="nonterminal_S" prod_rhs="a S"/>
    <cfg_step_label id="prod_2" prod_lhs="nonterminal_S" prod_rhs="a A P"/>
    <cfg_step_label id="prod_3" prod_lhs="nonterminal_P" prod_rhs="b"/>
    <cfg_step_label id="prod_4" prod_lhs="nonterminal_P" prod_rhs="b a"/>
    <cfg_step_label id="prod_5" prod_lhs="nonterminal_S" prod_rhs="A"/>
    <cfg_step_label id="prod_6" prod_lhs="nonterminal_A" prod_rhs="a A b a a"/>
    <cfg_step_label id="prod_7" prod_lhs="nonterminal_A"/>

    <cfg
            id="input"
            cfg_nonterminals="nonterminal_S nonterminal_P nonterminal_A"
            cfg_events="event_a event_b"
            cfg_initial="nonterminal_S"
            cfg_step_labels="prod_0 prod_1 prod_2 prod_3 prod_4 prod_5 prod_6 prod_7"/>

</root>

=== ControllerSynthesis/CoSy/src/test/resources/unit_tests/p01__ENFORCE_BLOCKFREE__T06_02_02_EDPDA_REMOVE_MASS_POPPING_EDGES___extra1.xml
<?xml version="1.0"?>
<root
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../main/resources/cosy.xsd">

    <!--
    author: Sven Schneider
    copyright: all rights reserved, 2018
    -->

    <symbol__cons_symbol_nat id="symbol__cons_symbol_nat-1" value="0"/>
    <symbol__cons_symbol_nat id="symbol__cons_symbol_nat-2" value="1"/>
    <symbol__cons_symbol_nat id="symbol__cons_symbol_nat-3" value="2"/>
    <symbol__cons_symbol_nat id="symbol__cons_symbol_nat-4" value="3"/>
    <string_symbol id="string_symbol-1" string="r"/>
    <string_symbol id="string_symbol-2" string="F"/>
    <string_symbol id="string_symbol-3" string="S"/>
    <string_symbol id="string_symbol-4" string="B1"/>
    <string_symbol id="string_symbol-5" string="B2"/>
    <string_symbol id="string_symbol-6" string="A"/>
    <epda_step_label id="epda_step_label-1" edge_src="symbol__cons_symbol_nat-1" edge_event="string_symbol-6"
                     edge_pop="symbol__cons_symbol_nat-3"
                     edge_push="symbol__cons_symbol_nat-1 symbol__cons_symbol_nat-3"
                     edge_trg="symbol__cons_symbol_nat-3"/>
    <epda_step_label id="epda_step_label-2" edge_src="symbol__cons_symbol_nat-4" edge_event="string_symbol-4"
                     edge_pop="symbol__cons_symbol_nat-2"
                     edge_push="symbol__cons_symbol_nat-4 symbol__cons_symbol_nat-2"
                     edge_trg="symbol__cons_symbol_nat-2"/>
    <epda_step_label id="epda_step_label-3" edge_src="symbol__cons_symbol_nat-3" edge_pop="symbol__cons_symbol_nat-1"
                     edge_push="symbol__cons_symbol_nat-2 symbol__cons_symbol_nat-1"
                     edge_trg="symbol__cons_symbol_nat-4"/>
    <epda id="input"
          epda_states="symbol__cons_symbol_nat-1 symbol__cons_symbol_nat-2 symbol__cons_symbol_nat-3 symbol__cons_symbol_nat-4"
          epda_events="string_symbol-1 string_symbol-2 string_symbol-3 string_symbol-4 string_symbol-5 string_symbol-6 symbol__cons_symbol_nat-1"
          epda_gamma="symbol__cons_symbol_nat-1 symbol__cons_symbol_nat-2 symbol__cons_symbol_nat-3 symbol__cons_symbol_nat-4"
          epda_delta="epda_step_label-1 epda_step_label-2 epda_step_label-3" epda_initial="symbol__cons_symbol_nat-1"
          epda_eos="symbol__cons_symbol_nat-3"/>
</root>

=== ControllerSynthesis/CoSy/src/test/resources/unit_tests/p01__ENFORCE_BLOCKFREE__T04_CFG_FIRST___FUNCFGFIRST_example_1.xml
<?xml version="1.0"?>
<root
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../main/resources/cosy.xsd">

    <!--
    author: Sven Schneider
    copyright: all rights reserved, 2018
    -->

    <string_symbol id="event_a" string="a"/>
    <string_symbol id="event_b" string="b"/>
    <string_symbol id="event_c" string="c"/>
    <two_elements__teB id="a" value="event_a"/>
    <two_elements__teB id="b" value="event_b"/>
    <two_elements__teB id="c" value="event_c"/>

    <string_symbol id="nonterminal_S" string="S"/>
    <string_symbol id="nonterminal_A" string="A"/>
    <string_symbol id="nonterminal_B" string="B"/>
    <two_elements__teA id="S" value="nonterminal_S"/>
    <two_elements__teA id="A" value="nonterminal_A"/>
    <two_elements__teA id="B" value="nonterminal_B"/>

    <cfg_step_label id="prod_0" prod_lhs="nonterminal_S" prod_rhs="a A"/>
    <cfg_step_label id="prod_1" prod_lhs="nonterminal_S" prod_rhs="B"/>
    <cfg_step_label id="prod_2" prod_lhs="nonterminal_A" prod_rhs="A c"/>
    <cfg_step_label id="prod_3" prod_lhs="nonterminal_A"/>
    <cfg_step_label id="prod_4" prod_lhs="nonterminal_B" prod_rhs="c B"/>
    <cfg_step_label id="prod_5" prod_lhs="nonterminal_B" prod_rhs="A"/>
    <cfg
            id="input"
            cfg_nonterminals="nonterminal_S nonterminal_A nonterminal_B"
            cfg_events="event_a event_b event_c"
            cfg_initial="nonterminal_S"
            cfg_step_labels="prod_0 prod_1 prod_2 prod_3 prod_4 prod_5"/>

</root>
